substitutions:
  _AR_REGION: europe-west1
  _AR_REPO: eurosat
  _IMAGE_NAME: gpu_cloud_storage_and_saving # default fallback
  _IMAGE_TAG: latest   # default fallback
  _DOCKER_FILE: dockerfiles/train_gpu.dockerfile # default fallback

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build container
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - .
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - -f
      - ${_DOCKER_FILE}

  - name: gcr.io/cloud-builders/docker
    id: Push container image
    args:
      - push
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}
