substitutions:
  _VERTEX_TRAIN_CONFIG: cloud_deploy/config_gpu.yaml
  _WANDB_ENTITY: s252840-danmarks-tekniske-universitet-dtu
  _IMAGE_TAG: latest   # default fallback

serviceAccount: projects/mlops-team-10/serviceAccounts/bucket-manager@mlops-team-10.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
      env: WANDB_API_KEY

steps:
  - name: alpine
    id: Replace values in config
    entrypoint: sh
    args:
      - -c
      - |
        apk add --no-cache gettext
        envsubst < ${_VERTEX_TRAIN_CONFIG} > ${_VERTEX_TRAIN_CONFIG}.tmp
        mv ${_VERTEX_TRAIN_CONFIG}.tmp ${_VERTEX_TRAIN_CONFIG}
    secretEnv:
      - WANDB_API_KEY

  - name: alpine
    id: Show config
    waitFor:
      - Replace values in config
    entrypoint: sh
    args:
      - -c
      - cat ${_VERTEX_TRAIN_CONFIG}

  - name: gcr.io/cloud-builders/gcloud
    id: Train on Vertex AI
    waitFor:
      - Replace values in config
    args:
      - ai
      - custom-jobs
      - create
      - --region=europe-west1
      - --display-name=GPU-Training
      - --service-account=bucket-manager@mlops-team-10.iam.gserviceaccount.com
      - --config=${_VERTEX_TRAIN_CONFIG}
